name: Protect File

on: 
  push:
    branches:
      - '**'  # Applies to all branches

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if restricted file was modified
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "Jenkinsfile"; then
            echo "The protected file has been modified. Rejecting push!"
            exit 1
          fi
